## Data Cleaning & Preprocessing

In [177]:
import pandas as pd
data = pd.read_csv("marketing/marketing_campaign.csv", sep="\t")
data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [178]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [179]:
data.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [180]:
#faire un copie de data pour ne pas toucher à l'original
copie=data.copy()

# Suppression des valeurs nulles

In [181]:
#d'apres les infos il y a des valeurs manquantes dans la colonne "Income" d'ou on va les supprimer car il sont trés negligables
copie = copie.dropna(subset=["Income"])

In [182]:
#longeur du dataframe après suppression des valeurs manquantes
print(len(copie))

2216

# Suppression des colonnes inutiles

In [183]:
#d'aprés le head j'ai remarqué que les colonnes "AcceptedCmp1","AcceptedCmp2","AcceptedCmp3","AcceptedCmp4","AcceptedCmp5","Complain","Response" contenaient bcp de valeurs nulles d'ou je vais les supprimer
copie["AcceptedCmp1"].value_counts()[0]
copie["Complain"].value_counts()[0]
copie["Response"].value_counts()[0]
copie = copie.drop(columns=["AcceptedCmp1","AcceptedCmp2","AcceptedCmp3","AcceptedCmp4","AcceptedCmp5","Complain","Response"])

In [184]:
#j'ai constater que les colonnes "Z_Revenue" et "Z_CostContact" contiennent la meme veleur ds toutes les lignes d'ou je vais les supprimer
copie.Z_Revenue.value_counts()
copie.Z_CostContact.value_counts()
copie.drop(columns=["Z_CostContact","Z_Revenue"], inplace=True)

In [185]:
copie.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,546,172,88,88,3,8,10,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,6,2,1,6,2,1,1,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,127,111,21,42,1,8,2,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,20,10,3,5,2,2,0,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,118,46,27,15,5,5,3,6,5

# Encodage des valeurs categorielle

In [186]:
#mainteant je vais faire le traitement de la colonne "Education" pour la convertir en numérique
copie.Education.value_counts() #j'ai commencer par voir les différentes catégories de la colonne "Education"

Education
Graduation    1116
PhD            481
Master         365
2n Cycle       200
Basic           54
Name: count, dtype: int64

In [187]:
#maintenant pour les valeur categorielle je vais faire un ordianl encoding pour les transformer en valeur numerique (plus significatif))
mapping = {"Basic":1, "2n Cycle":2, "Graduation":3, "Master":4, "PhD":5}
copie["Education_encoded"] = copie["Education"].map(mapping)

In [188]:
#meme chose pour la colonne "Marital_Status"
copie.Marital_Status.value_counts()

Marital_Status
Married     857
Together    573
Single      471
Divorced    232
Widow        76
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [189]:
copie["Marital_Status"] = copie["Marital_Status"].replace(["YOLO","Absurd","alone"], "Other")

In [190]:
mapping = {"Single":1, "Together":2, "Married":3, "Divorced":4, "Widow":5, "Other":0}
copie["Marital_Status_encoded"] = copie["Marital_Status"].map(mapping)

# Feature engineering

In [191]:
from datetime import datetime
#d'apres la colonne "Year_Birth" on peut calculer l'age de chaque client pour avoir une meilleure idée sur la distribution d'age dans notre dataset
current_year = datetime.now().year
copie["Age"] = current_year - copie["Year_Birth"]

print(copie[["Year_Birth", "Age"]].head())

   Year_Birth  Age
0        1957   69
1        1954   72
2        1965   61
3        1984   42
4        1981   45

In [192]:
#maintenant on peut faire le meme chose pour la colonne "Dt_Customer" pour calculer le nombre d'année d'enrollement de chaque client
copie["Dt_Customer"] = pd.to_datetime(copie["Dt_Customer"], format="%d-%m-%Y")
current_date = datetime.now()
copie["nbr_enrolment _year"] = ((current_date - copie["Dt_Customer"]).dt.days // 365)

print(copie[["Dt_Customer", "nbr_enrolment _year"]].head())

  Dt_Customer  nbr_enrolment _year
0  2012-09-04                   13
1  2014-03-08                   12
2  2013-08-21                   12
3  2014-02-10                   12
4  2014-01-19                   12

In [193]:
#j'ai supprimer les colonnes "Year_Birth","Dt_Customer","Education","Marital_Status","ID" car elles sont soit redondantes ou pas utiles pour l'analyse
copie.drop(columns=["Year_Birth","Dt_Customer","Education","Marital_Status","ID"], inplace=True)

In [194]:
copie.head()

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Education_encoded,Marital_Status_encoded,Age,nbr_enrolment _year
0,58138.0,0,0,58,635,88,546,172,88,88,3,8,10,4,7,3,1.0,69,13
1,46344.0,1,1,38,11,1,6,2,1,6,2,1,1,2,5,3,1.0,72,12
2,71613.0,0,0,26,426,49,127,111,21,42,1,8,2,10,4,3,2.0,61,12
3,26646.0,1,0,26,11,4,20,10,3,5,2,2,0,4,6,3,2.0,42,12
4,58293.0,1,0,94,173,43,118,46,27,15,5,5,3,6,5,5,3.0,45,12

In [195]:
#maintenat tous les données sont numerique d'ou on va faire standardisation pour les mettre à la même échelle
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
copie_scaled = scaler.fit_transform(copie)

In [196]:
#resultats aprés nettoyage et standardisation
copie_scaled=pd.DataFrame(copie_scaled, columns=copie.columns)
copie_scaled.head()

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Education_encoded,Marital_Status_encoded,Age,nbr_enrolment _year
0,0.234063,-0.823039,-0.928972,0.310532,0.978226,1.549429,1.690227,2.454568,1.484827,0.850031,0.351713,1.428553,2.504712,-0.554143,0.693232,-0.457733,-1.413206,0.986443,1.148677
1,-0.234559,1.039938,0.909066,-0.380509,-0.872024,-0.637328,-0.717986,-0.651038,-0.633880,-0.732867,-0.168231,-1.125881,-0.571082,-1.169518,-0.131574,-0.457733,-1.413206,1.236801,-0.399661
2,0.769478,-0.823039,-0.928972,-0.795134,0.358511,0.569159,-0.178368,1.340203,-0.146821,-0.037937,-0.688176,1.428553,-0.229327,1.291982,-0.543978,-0.457733,-0.460594,0.318822,-0.399661
3,-1.017239,1.039938,-0.928972,-0.795134,-0.872024,-0.561922,-0.655551,-0.504892,-0.585174,-0.752171,-0.168231,-0.760962,-0.912837,-0.554143,0.280829,-0.457733,-0.460594,-1.266777,-0.399661
4,0.240221,1.039938,-0.928972,1.554407,-0.391671,0.418348,-0.218505,0.152766,-0.000703,-0.559135,1.391603,0.333796,0.112428,0.061232,-0.131574,1.533113,0.492018,-1.016420,-0.399661

In [197]:
copie_scaled.to_csv("marketing/marketing_campaign_cleaned.csv", index=False)